<?xml version="1.0"?>
<package format="3">
  <name>fetch_navigation</name>
  <version>0.9.0</version>
  <description>ROS 2 Nav2 configuration and launch files for Fetch.</description>

  <maintainer email="opensource@fetchrobotics.com">Fetch Robotics Open Source Team</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>fetch_stockroom_robot</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
