controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_with_torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_with_torso_controller:
  ros__parameters:
    joints:
      - torso_lift_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    open_loop_control: false
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.02

gripper_controller:
  ros__parameters:
    joints:
      - l_gripper_finger_joint
      - r_gripper_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01

head_controller:
  ros__parameters:
    joints:
      - head_pan_joint
      - head_tilt_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.02
